org: Modus-sandbox
repos:
  - name: sarath-test
    # (optional) create/update a repo ruleset targeting branches
    ruleset:
      name: "Master"
      enforcement: active          # active | disabled (default: active)
      target_branches:             # ref patterns; "~DEFAULT_BRANCH" is allowed
        - "~DEFAULT_BRANCH"
      # Rules you want applied (only those present are sent)
      require_deployments:         # "Require deployments to succeed"
        - "prod"
      require_pull_request: true   # "Require a pull request before merging"
      block_force_pushes: true     # "Block force pushes"
      restrict_deletions: true     # "Restrict deletions"
      # Optional: Status checks (names must match the check run contexts)
      # require_status_checks:
      #   - "build"
      #   - "test"

    environments:
      dev:
        API_KEY: "blah"
        SIMPLE_SECRET: "plain-string-secret"
      prod:
        DB_PASSWORD:
          file: "db_password.txt"
        API_URL:
          value: "https://api.example.com"
    teams:
      - slug: gth_dhb_admin
        permission: Admin     # maps to "push"
      - slug: gth_dhb_maintain
        permission: Read      # maps to "pull"
      - slug: gth_dhb_user
        permission: Maintain
