name: Release Github Bulk Env Updator

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'
          cache: true

      - name: Resolve modules
        run: go mod tidy

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            ext=".exe"
          fi
          name="gh-env-secrets-${{ matrix.goos }}-${{ matrix.goarch }}"
          out="dist/${name}${ext}"
          zip="dist/${name}.zip"

          # Build (pure Go sealed-box with x/crypto)
          go build -o "${out}" ./main.go

          # Package
          zip -j "${zip}" "${out}"

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
